export const entityList = [
  {
    id: 1,
    name: "TechVision Ltda",
    telephone: "(11) 3222-4455",
    email: "contato@techvision.com",
    createdAt: "2023-01-15T09:30:00",
    address: "Av. Paulista, 1000 - São Paulo/SP",
    disabled: false,
    description: "Empresa de tecnologia especializada em soluções de software corporativo e consultoria em transformação digital.",
  },
  {
    id: 2,
    name: "EcoSolutions Brasil",
    telephone: "(21) 4002-8922",
    email: "suporte@ecosolutions.com.br",
    createdAt: "2022-11-20T14:15:00",
    address: "Rua das Flores, 200 - Rio de Janeiro/RJ",
    disabled: true,
    description: "Consultoria em sustentabilidade e soluções ecológicas para empresas que buscam reduzir seu impacto ambiental.",
  },
  {
    id: 3,
    name: "AgroMax Agropecuária",
    telephone: "(62) 3333-7777",
    email: "vendas@agromax.com",
    createdAt: "2023-03-05T08:45:00",
    address: "Rodovia BR-153, Km 45 - Goiânia/GO",
    disabled: false,
    description: "Produtora e distribuidora de insumos agrícolas, oferecendo sementes, fertilizantes e suporte técnico para o campo.",
  },
  {
    id: 4,
    name: "InovaSoft Tecnologia",
    telephone: "(31) 98888-5566",
    email: "inova@inovasoft.com",
    createdAt: "2023-04-12T11:00:00",
    address: "Av. Afonso Pena, 3500 - Belo Horizonte/MG",
    disabled: false,
    description: "Startup focada em desenvolvimento de aplicativos móveis e soluções em nuvem para empresas de médio porte.",
  },
  {
    id: 5,
    name: "Construmax Engenharia",
    telephone: "(41) 3232-9090",
    email: "engenharia@construmax.com",
    createdAt: "2022-09-28T16:20:00",
    address: "Rua XV de Novembro, 45 - Curitiba/PR",
    disabled: false,
    description: "Empresa de engenharia e construção civil com experiência em obras de grande porte e projetos de infraestrutura.",
  },
  {
    id: 6,
    name: "MedCare Saúde",
    telephone: "(85) 4009-7788",
    email: "contato@medcare.com.br",
    createdAt: "2023-02-08T10:10:00",
    address: "Av. Beira Mar, 800 - Fortaleza/CE",
    disabled: false,
    description: "Rede de clínicas médicas e laboratórios que oferece atendimento especializado em diversas áreas da saúde.",
  },
  {
    id: 7,
    name: "EducaMais Ensino",
    telephone: "(71) 3123-5566",
    email: "matriculas@educamais.com",
    createdAt: "2022-12-14T09:00:00",
    address: "Av. Sete de Setembro, 1200 - Salvador/BA",
    disabled: false,
    description: "Instituição de ensino com foco em cursos técnicos e profissionalizantes para jovens e adultos.",
  },
  {
    id: 8,
    name: "SolarTech Energia",
    telephone: "(48) 4000-1212",
    email: "energia@solartech.com",
    createdAt: "2023-05-22T15:30:00",
    address: "Rua das Palmeiras, 88 - Florianópolis/SC",
    disabled: false,
    description: "Empresa de energia renovável especializada na instalação de sistemas fotovoltaicos residenciais e comerciais.",
  },
  {
    id: 9,
    name: "Prime Consultoria",
    telephone: "(51) 3555-6677",
    email: "atendimento@primeconsult.com",
    createdAt: "2023-07-01T13:45:00",
    address: "Av. Borges de Medeiros, 600 - Porto Alegre/RS",
    disabled: false,
    description: "Consultoria empresarial voltada para gestão financeira, recursos humanos e planejamento estratégico.",
  },
  {
    id: 10,
    name: "FoodPlus Alimentos",
    telephone: "(19) 3334-2221",
    email: "sac@foodplus.com",
    createdAt: "2022-10-18T11:20:00",
    address: "Rua do Comércio, 300 - Campinas/SP",
    disabled: false,
    description: "Indústria alimentícia com foco em alimentos congelados e snacks saudáveis.",
  },
  {
    id: 11,
    name: "AutoPrime Veículos",
    telephone: "(16) 3221-8899",
    email: "contato@autoprime.com",
    createdAt: "2023-08-19T10:40:00",
    address: "Av. Independência, 750 - Ribeirão Preto/SP",
    disabled: false,
    description: "Concessionária multimarcas com serviços de venda, financiamento e manutenção de veículos.",
  },
  {
    id: 12,
    name: "LogisTech Transportes",
    telephone: "(92) 4005-4444",
    email: "fretes@logistech.com",
    createdAt: "2023-01-10T08:50:00",
    address: "Rua Manaus Moderna, 400 - Manaus/AM",
    disabled: false,
    description: "Transportadora com atuação nacional, especializada em logística integrada e transporte de cargas.",
  },
  {
    id: 13,
    name: "ModaVip Confecções",
    telephone: "(84) 3111-2200",
    email: "vendas@modavip.com",
    createdAt: "2022-07-30T14:10:00",
    address: "Rua João Pessoa, 99 - Natal/RN",
    disabled: false,
    description: "Marca de moda especializada em roupas femininas e acessórios para o público jovem.",
  },
  {
    id: 14,
    name: "CleanPro Higienização",
    telephone: "(95) 3122-3344",
    email: "orcamento@cleanpro.com",
    createdAt: "2023-06-05T09:30:00",
    address: "Av. Ville Roy, 1020 - Boa Vista/RR",
    disabled: false,
    description: "Empresa especializada em higienização de estofados, carpetes e ambientes corporativos.",
  },
  {
    id: 15,
    name: "BioLife Farmacêutica",
    telephone: "(98) 4001-2323",
    email: "contato@biolife.com",
    createdAt: "2023-03-28T11:15:00",
    address: "Av. dos Holandeses, 500 - São Luís/MA",
    disabled: false,
    description: "Indústria farmacêutica voltada para medicamentos genéricos e biotecnologia.",
  },
  {
    id: 16,
    name: "Oceanic Pescados",
    telephone: "(82) 3344-6677",
    email: "sac@oceanic.com",
    createdAt: "2022-11-07T12:00:00",
    address: "Av. da Paz, 150 - Maceió/AL",
    disabled: false,
    description: "Distribuidora de pescados frescos e congelados para supermercados e restaurantes.",
  },
  {
    id: 17,
    name: "UrbanMob Mobilidade",
    telephone: "(13) 3555-8899",
    email: "contato@urbanmob.com",
    createdAt: "2023-09-02T10:50:00",
    address: "Av. Ana Costa, 420 - Santos/SP",
    disabled: false,
    description: "Startup de mobilidade urbana com soluções em aplicativos de transporte coletivo e compartilhado.",
  },
  {
    id: 18,
    name: "GreenLand Paisagismo",
    telephone: "(47) 3222-5566",
    email: "suporte@greenland.com",
    createdAt: "2023-02-14T08:30:00",
    address: "Rua Blumenau, 300 - Joinville/SC",
    disabled: false,
    description: "Empresa de jardinagem e paisagismo que desenvolve projetos residenciais e comerciais.",
  },
  {
    id: 19,
    name: "SmartPay Fintech",
    telephone: "(61) 4008-9999",
    email: "financeiro@smartpay.com",
    createdAt: "2023-05-18T13:20:00",
    address: "Setor Comercial Sul, Quadra 2 - Brasília/DF",
    disabled: false,
    description: "Fintech especializada em meios de pagamento digitais e soluções para e-commerce.",
  },
  {
    id: 20,
    name: "PetLovers Petshop",
    telephone: "(27) 3233-1122",
    email: "contato@petlovers.com",
    createdAt: "2023-07-25T11:45:00",
    address: "Av. Nossa Senhora da Penha, 800 - Vitória/ES",
    disabled: false,
    description: "Rede de petshops com serviços de banho, tosa e venda de produtos para animais de estimação.",
  },
];

export const historyList = [
    {
      groupId: 101,
      fiscalNote: "NF-2025-001",
      itemId: 1,
      itemName: "Caneta Azul",
      user: "ana@example.com",
      date: "2025-09-25T09:15:00",
      quantity: 10,
    },
    {
      groupId: 101,
      fiscalNote: "NF-2025-002",
      itemId: 2,
      itemName: "Caderno Pautado",
      user: "bruno@example.com",
      date: "2025-09-25T10:20:00",
      quantity: 5,
      disabled: true,
    },
    {
      groupId: 102,
      fiscalNote: "NF-2025-003",
      itemId: 3,
      itemName: "Lápis HB",
      user: "carla@example.com",
      date: "2025-09-24T14:45:00",
      quantity: 20,
    },
    {
      groupId: 103,
      fiscalNote: "NF-2025-004",
      itemId: 4,
      itemName: "Borracha",
      user: "daniel@example.com",
      date: "2025-09-24T16:30:00",
      quantity: 15,
    },
    {
      groupId: 104,
      fiscalNote: "NF-2025-005",
      itemId: 5,
      itemName: "Marcador Permanente",
      user: "eduardo@example.com",
      date: "2025-09-23T11:00:00",
      quantity: 8,
    },
    {
      groupId: 105,
      fiscalNote: "NF-2025-006",
      itemId: 6,
      itemName: "Apontador",
      user: "fernanda@example.com",
      date: "2025-09-23T13:15:00",
      quantity: 12,
    },
    {
      groupId: 101,
      fiscalNote: "NF-2025-007",
      itemId: 7,
      itemName: "Régua 30cm",
      user: "gabriel@example.com",
      date: "2025-09-22T09:50:00",
      quantity: 7,
      disabled: true,
    },
    {
      groupId: 102,
      fiscalNote: "NF-2025-008",
      itemId: 8,
      itemName: "Agenda 2025",
      user: "heloisa@example.com",
      date: "2025-09-22T15:10:00",
      quantity: 18,
    },
    {
      groupId: 103,
      fiscalNote: "NF-2025-009",
      itemId: 9,
      itemName: "Post-it 3x3",
      user: "igor@example.com",
      date: "2025-09-21T10:40:00",
      quantity: 25,
    },
    {
      groupId: 104,
      fiscalNote: "NF-2025-010",
      itemId: 10,
      itemName: "Clip de Papel",
      user: "juliana@example.com",
      date: "2025-09-21T12:55:00",
      quantity: 6,
    },
    {
      groupId: 105,
      fiscalNote: "NF-2025-011",
      itemId: 11,
      itemName: "Papel A4",
      user: "kaio@example.com",
      date: "2025-09-20T09:30:00",
      quantity: 14,
    },
    {
      groupId: 101,
      fiscalNote: "NF-2025-012",
      itemId: 12,
      itemName: "Envelope",
      user: "larissa@example.com",
      date: "2025-09-20T11:25:00",
      quantity: 9,
    },
    {
      groupId: 102,
      fiscalNote: "NF-2025-013",
      itemId: 13,
      itemName: "Fita Adesiva",
      user: "marcos@example.com",
      date: "2025-09-19T14:15:00",
      quantity: 22,
      disabled: true,
    },
    {
      groupId: 103,
      fiscalNote: "NF-2025-014",
      itemId: 14,
      itemName: "Bloco de Notas",
      user: "natalia@example.com",
      date: "2025-09-19T16:40:00",
      quantity: 11,
    },
    {
      groupId: 104,
      fiscalNote: "NF-2025-015",
      itemId: 15,
      itemName: "Tesoura",
      user: "octavio@example.com",
      date: "2025-09-18T10:05:00",
      quantity: 17,
    },
    {
      groupId: 105,
      fiscalNote: "NF-2025-016",
      itemId: 16,
      itemName: "Cola em Bastão",
      user: "paula@example.com",
      date: "2025-09-18T12:50:00",
      quantity: 20,
    },
    {
      groupId: 101,
      fiscalNote: "NF-2025-017",
      itemId: 17,
      itemName: "Marcador Quadro Branco",
      user: "quiteria@example.com",
      date: "2025-09-17T09:20:00",
      quantity: 13,
    },
    {
      groupId: 102,
      fiscalNote: "NF-2025-018",
      itemId: 18,
      itemName: "Caderno de Matemática",
      user: "rafael@example.com",
      date: "2025-09-17T14:30:00",
      quantity: 8,
      disabled: true,
    },
    {
      groupId: 103,
      fiscalNote: "NF-2025-019",
      itemId: 19,
      itemName: "Lápis de Cor",
      user: "sandra@example.com",
      date: "2025-09-16T11:45:00",
      quantity: 19,
    },
    {
      groupId: 104,
      fiscalNote: "NF-2025-020",
      itemId: 20,
      itemName: "Estojo",
      user: "thiago@example.com",
      date: "2025-09-16T13:55:00",
      quantity: 16,
    },
  ]

export const itemList = [
  {
    id: 1,
    name: "Sensor de Temperatura",
    position: "Linha de Produção A",
    manufacturer: "TechVision Ltda",
    segment: "Eletrônicos",
    group: "Sensores Industriais",
    quantity: 50,
    alertQuantity: 10,
    unit: "unidade",
    disabled: false,
    description: "Sensor digital de temperatura para controle de processos industriais.",
    createdAt: "2025-01-15T10:30:00"
  },
  {
    id: 2,
    name: "Motor Elétrico 5HP",
    position: "Setor Mecânico",
    manufacturer: "InovaSoft Tecnologia",
    segment: "Automação",
    group: "Motores e Acionamentos",
    quantity: 15,
    alertQuantity: 5,
    unit: "unidade",
    disabled: false,
    description: "Motor trifásico de 5 cavalos de potência utilizado em esteiras automáticas.",
    createdAt: "2025-01-20T14:15:00"
  },
  {
    id: 3,
    name: "Válvula de Pressão",
    position: "Linha de Montagem B",
    manufacturer: "Construmax Engenharia",
    segment: "Industrial",
    group: "Válvulas e Acessórios",
    quantity: 35,
    alertQuantity: 8,
    unit: "unidade",
    disabled: true,
    description: "Válvula reguladora de pressão para sistemas hidráulicos industriais.",
    createdAt: "2025-02-05T09:45:00"
  },
  {
    id: 4,
    name: "Painel de Controle",
    position: "Central de Automação",
    manufacturer: "SmartPay Fintech",
    segment: "Elétrica",
    group: "Painéis de Controle",
    quantity: 10,
    alertQuantity: 2,
    unit: "unidade",
    disabled: false,
    description: "Painel de automação com interface digital para monitoramento remoto.",
    createdAt: "2025-02-10T11:20:00"
  },
  {
    id: 5,
    name: "Cabo de Energia 2mm",
    position: "Depósito 01",
    manufacturer: "SolarTech Energia",
    segment: "Elétrica",
    group: "Cabos e Fios",
    quantity: 200,
    alertQuantity: 50,
    unit: "metro",
    disabled: false,
    description: "Cabo de cobre flexível utilizado em instalações de painéis solares.",
    createdAt: "2025-02-12T08:45:00"
  },
  {
    id: 6,
    name: "Placa de Circuito",
    position: "Montagem Eletrônica",
    manufacturer: "TechVision Ltda",
    segment: "Eletrônicos",
    group: "Placas Eletrônicas",
    quantity: 75,
    alertQuantity: 15,
    unit: "unidade",
    disabled: false,
    description: "Placa de circuito impresso utilizada em dispositivos IoT.",
    createdAt: "2025-02-18T13:30:00"
  },
  {
    id: 7,
    name: "Bomba Hidráulica",
    position: "Oficina 2",
    manufacturer: "AgroMax Agropecuária",
    segment: "Mecânica",
    group: "Bombas e Compressores",
    quantity: 20,
    alertQuantity: 5,
    unit: "unidade",
    disabled: false,
    description: "Bomba hidráulica de alta pressão usada em tratores e implementos agrícolas.",
    createdAt: "2025-02-22T16:10:00"
  },
  {
    id: 8,
    name: "Transmissor de Sinal",
    position: "Sala de Controle",
    manufacturer: "LogisTech Transportes",
    segment: "Telecom",
    group: "Comunicação",
    quantity: 40,
    alertQuantity: 10,
    unit: "unidade",
    disabled: false,
    description: "Equipamento de comunicação sem fio utilizado no rastreamento de cargas.",
    createdAt: "2025-03-01T09:15:00"
  },
  {
    id: 9,
    name: "Módulo Wi-Fi Industrial",
    position: "Setor de Testes",
    manufacturer: "InovaSoft Tecnologia",
    segment: "IoT",
    group: "Módulos de Comunicação",
    quantity: 60,
    alertQuantity: 12,
    unit: "unidade",
    disabled: true,
    description: "Módulo de conectividade para sistemas de monitoramento remoto.",
    createdAt: "2025-03-05T14:40:00"
  },
  {
    id: 10,
    name: "Controlador Lógico (CLP)",
    position: "Painel 3",
    manufacturer: "Prime Consultoria",
    segment: "Automação",
    group: "Controladores",
    quantity: 18,
    alertQuantity: 4,
    unit: "unidade",
    disabled: false,
    description: "Controlador lógico programável para automação de processos industriais.",
    createdAt: "2025-03-08T10:25:00"
  },
  {
    id: 11,
    name: "Ventilador Industrial",
    position: "Área de Ventilação",
    manufacturer: "Construmax Engenharia",
    segment: "Industrial",
    group: "Ventilação e Refrigeração",
    quantity: 12,
    alertQuantity: 3,
    unit: "unidade",
    disabled: false,
    description: "Equipamento para resfriamento de ambientes industriais de grande porte.",
    createdAt: "2025-03-12T11:50:00"
  },
  {
    id: 12,
    name: "Compressor de Ar",
    position: "Manutenção Geral",
    manufacturer: "AutoPrime Veículos",
    segment: "Oficina",
    group: "Bombas e Compressores",
    quantity: 8,
    alertQuantity: 2,
    unit: "unidade",
    disabled: false,
    description: "Compressor de ar para limpeza e pressurização de sistemas.",
    createdAt: "2025-03-15T15:35:00"
  },
  {
    id: 13,
    name: "Luminária LED",
    position: "Depósito 2",
    manufacturer: "SolarTech Energia",
    segment: "Iluminação",
    group: "Iluminação Industrial",
    quantity: 150,
    alertQuantity: 30,
    unit: "unidade",
    disabled: false,
    description: "Luminária de alta eficiência energética para galpões industriais.",
    createdAt: "2025-03-18T08:20:00"
  },
  {
    id: 14,
    name: "Rolamento de Esferas",
    position: "Almoxarifado",
    manufacturer: "AgroMax Agropecuária",
    segment: "Mecânica",
    group: "Rolamentos e Mancais",
    quantity: 90,
    alertQuantity: 20,
    unit: "unidade",
    disabled: false,
    description: "Rolamento de alta durabilidade utilizado em maquinários agrícolas.",
    createdAt: "2025-03-22T13:05:00"
  },
  {
    id: 15,
    name: "Sensor Ultrassônico",
    position: "Linha de Robótica",
    manufacturer: "InovaSoft Tecnologia",
    segment: "Automação",
    group: "Sensores Industriais",
    quantity: 25,
    alertQuantity: 6,
    unit: "unidade",
    disabled: false,
    description: "Sensor para detecção de distância em robôs industriais.",
    createdAt: "2025-03-25T16:45:00"
  },
  {
    id: 16,
    name: "Filtro de Ar",
    position: "Setor de Climatização",
    manufacturer: "MedCare Saúde",
    segment: "Manutenção",
    group: "Filtros e Purificadores",
    quantity: 55,
    alertQuantity: 12,
    unit: "unidade",
    disabled: false,
    description: "Filtro de ar de alta eficiência para sistemas de ventilação hospitalar.",
    createdAt: "2025-03-28T10:10:00"
  },
  {
    id: 17,
    name: "Cabine Acústica",
    position: "Laboratório de Testes",
    manufacturer: "CleanPro Higienização",
    segment: "Infraestrutura",
    group: "Cabines e Enclosures",
    quantity: 4,
    alertQuantity: 1,
    unit: "unidade",
    disabled: true,
    description: "Cabine isolada para medições de ruído em equipamentos industriais.",
    createdAt: "2025-04-02T14:25:00"
  },
  {
    id: 18,
    name: "Sensor de Umidade",
    position: "Estufa 2",
    manufacturer: "GreenLand Paisagismo",
    segment: "Agronegócio",
    group: "Sensores Agrícolas",
    quantity: 32,
    alertQuantity: 8,
    unit: "unidade",
    disabled: false,
    description: "Sensor digital para monitoramento de umidade em estufas agrícolas.",
    createdAt: "2025-04-05T09:40:00"
  },
  {
    id: 19,
    name: "Painel Solar 550W",
    position: "Campo Solar 01",
    manufacturer: "SolarTech Energia",
    segment: "Energia",
    group: "Energia Solar",
    quantity: 24,
    alertQuantity: 5,
    unit: "unidade",
    disabled: false,
    description: "Painel solar monocristalino de alta eficiência para geração fotovoltaica.",
    createdAt: "2025-04-08T12:15:00"
  },
  {
    id: 20,
    name: "Cabo de Rede Cat6",
    position: "TI - Rack 4",
    manufacturer: "TechVision Ltda",
    segment: "TI",
    group: "Cabos e Fios",
    quantity: 300,
    alertQuantity: 60,
    unit: "metro",
    disabled: false,
    description: "Cabo de rede de alta velocidade para sistemas corporativos.",
    createdAt: "2025-04-10T15:50:00"
  },
];

export const itemHistoryList = [
  {
    groupId: 201,
    fiscalNote: "NF-2025-101",
    itemId: 1,
    itemName: "Sensor de Temperatura",
    user: "tecnico.ana@empresa.com",
    date: "2025-09-25T09:15:00",
    quantity: 50,
    type: "entrada"
  },
  {
    groupId: 201,
    fiscalNote: "NF-2025-102",
    itemId: 2,
    itemName: "Placa de Circuito Impresso",
    user: "eng.bruno@empresa.com",
    date: "2025-09-25T10:20:00",
    quantity: 25,
    type: "saída",
    disabled: true,
  },
  {
    groupId: 202,
    fiscalNote: "NF-2025-103",
    itemId: 3,
    itemName: "Cabo de Energia 2mm",
    user: "eletricista.carla@empresa.com",
    date: "2025-09-24T14:45:00",
    quantity: 100,
    type: "entrada"
  },
  {
    groupId: 203,
    fiscalNote: "NF-2025-104",
    itemId: 4,
    itemName: "Resistor 10kΩ",
    user: "tec.daniel@empresa.com",
    date: "2025-09-24T16:30:00",
    quantity: 500,
    type: "entrada"
  },
  {
    groupId: 204,
    fiscalNote: "NF-2025-105",
    itemId: 5,
    itemName: "LED Vermelho 5mm",
    user: "montador.eduardo@empresa.com",
    date: "2025-09-23T11:00:00",
    quantity: 200,
    type: "saída"
  },
  {
    groupId: 205,
    fiscalNote: "NF-2025-106",
    itemId: 6,
    itemName: "Capacitor 100μF",
    user: "tec.fernanda@empresa.com",
    date: "2025-09-23T13:15:00",
    quantity: 150,
    type: "entrada"
  },
  {
    groupId: 201,
    fiscalNote: "NF-2025-107",
    itemId: 7,
    itemName: "Display LCD 16x2",
    user: "projetista.gabriel@empresa.com",
    date: "2025-09-22T09:50:00",
    quantity: 30,
    type: "saída",
    disabled: true,
  },
  {
    groupId: 202,
    fiscalNote: "NF-2025-108",
    itemId: 8,
    itemName: "Fonte Chaveada 12V",
    user: "eletricista.heloisa@empresa.com",
    date: "2025-09-22T15:10:00",
    quantity: 15,
    type: "entrada"
  },
  {
    groupId: 203,
    fiscalNote: "NF-2025-109",
    itemId: 9,
    itemName: "Microcontrolador ESP32",
    user: "dev.igor@empresa.com",
    date: "2025-09-21T10:40:00",
    quantity: 40,
    type: "entrada"
  },
  {
    groupId: 204,
    fiscalNote: "NF-2025-110",
    itemId: 10,
    itemName: "Conector USB Type-C",
    user: "montador.juliana@empresa.com",
    date: "2025-09-21T12:55:00",
    quantity: 80,
    type: "saída"
  },
  {
    groupId: 205,
    fiscalNote: "NF-2025-111",
    itemId: 11,
    itemName: "Transformador 220V/12V",
    user: "eletricista.kaio@empresa.com",
    date: "2025-09-20T09:30:00",
    quantity: 10,
    type: "entrada"
  },
  {
    groupId: 201,
    fiscalNote: "NF-2025-112",
    itemId: 12,
    itemName: "Sensor de Movimento PIR",
    user: "seguranca.larissa@empresa.com",
    date: "2025-09-20T11:25:00",
    quantity: 35,
    type: "entrada"
  },
  {
    groupId: 202,
    fiscalNote: "NF-2025-113",
    itemId: 13,
    itemName: "Relé 5V",
    user: "controle.marcos@empresa.com",
    date: "2025-09-19T14:15:00",
    quantity: 60,
    type: "saída",
    disabled: true,
  },
  {
    groupId: 203,
    fiscalNote: "NF-2025-114",
    itemId: 14,
    itemName: "Cristal Oscilador 16MHz",
    user: "clock.natalia@empresa.com",
    date: "2025-09-19T16:40:00",
    quantity: 45,
    type: "entrada"
  },
  {
    groupId: 204,
    fiscalNote: "NF-2025-115",
    itemId: 15,
    itemName: "Diodo 1N4007",
    user: "retificador.octavio@empresa.com",
    date: "2025-09-18T10:05:00",
    quantity: 300,
    type: "saída"
  },
  {
    groupId: 205,
    fiscalNote: "NF-2025-116",
    itemId: 16,
    itemName: "Potenciômetro 10kΩ",
    user: "ajuste.paula@empresa.com",
    date: "2025-09-18T12:50:00",
    quantity: 75,
    type: "entrada"
  },
  {
    groupId: 201,
    fiscalNote: "NF-2025-117",
    itemId: 17,
    itemName: "Módulo Bluetooth HC-05",
    user: "comunicacao.quiteria@empresa.com",
    date: "2025-09-17T09:20:00",
    quantity: 20,
    type: "entrada"
  },
  {
    groupId: 202,
    fiscalNote: "NF-2025-118",
    itemId: 18,
    itemName: "Fonte Linear 5V",
    user: "alimentacao.rafael@empresa.com",
    date: "2025-09-17T14:30:00",
    quantity: 12,
    type: "saída",
    disabled: true,
  },
  {
    groupId: 203,
    fiscalNote: "NF-2025-119",
    itemId: 19,
    itemName: "Sensor de Umidade DHT11",
    user: "ambiente.sandra@empresa.com",
    date: "2025-09-16T11:45:00",
    quantity: 25,
    type: "entrada"
  },
  {
    groupId: 204,
    fiscalNote: "NF-2025-120",
    itemId: 20,
    itemName: "Cooler 12V",
    user: "ventilacao.thiago@empresa.com",
    date: "2025-09-16T13:55:00",
    quantity: 18,
    type: "saída"
  },
]