export const entityList = [
  {
    id: 1,
    name: "TechVision Ltda",
    telephone: "(11) 3222-4455",
    email: "contato@techvision.com",
    createdAt: "2023-01-15T09:30:00",
    address: "Av. Paulista, 1000 - São Paulo/SP",
    disabled: false,
    description: "Empresa de tecnologia especializada em soluções de software corporativo e consultoria em transformação digital.",
  },
  {
    id: 2,
    name: "EcoSolutions Brasil",
    telephone: "(21) 4002-8922",
    email: "suporte@ecosolutions.com.br",
    createdAt: "2022-11-20T14:15:00",
    address: "Rua das Flores, 200 - Rio de Janeiro/RJ",
    disabled: true,
    description: "Consultoria em sustentabilidade e soluções ecológicas para empresas que buscam reduzir seu impacto ambiental.",
  },
  {
    id: 3,
    name: "AgroMax Agropecuária",
    telephone: "(62) 3333-7777",
    email: "vendas@agromax.com",
    createdAt: "2023-03-05T08:45:00",
    address: "Rodovia BR-153, Km 45 - Goiânia/GO",
    disabled: false,
    description: "Produtora e distribuidora de insumos agrícolas, oferecendo sementes, fertilizantes e suporte técnico para o campo.",
  },
  {
    id: 4,
    name: "InovaSoft Tecnologia",
    telephone: "(31) 98888-5566",
    email: "inova@inovasoft.com",
    createdAt: "2023-04-12T11:00:00",
    address: "Av. Afonso Pena, 3500 - Belo Horizonte/MG",
    disabled: false,
    description: "Startup focada em desenvolvimento de aplicativos móveis e soluções em nuvem para empresas de médio porte.",
  },
  {
    id: 5,
    name: "Construmax Engenharia",
    telephone: "(41) 3232-9090",
    email: "engenharia@construmax.com",
    createdAt: "2022-09-28T16:20:00",
    address: "Rua XV de Novembro, 45 - Curitiba/PR",
    disabled: false,
    description: "Empresa de engenharia e construção civil com experiência em obras de grande porte e projetos de infraestrutura.",
  },
  {
    id: 6,
    name: "MedCare Saúde",
    telephone: "(85) 4009-7788",
    email: "contato@medcare.com.br",
    createdAt: "2023-02-08T10:10:00",
    address: "Av. Beira Mar, 800 - Fortaleza/CE",
    disabled: false,
    description: "Rede de clínicas médicas e laboratórios que oferece atendimento especializado em diversas áreas da saúde.",
  },
  {
    id: 7,
    name: "EducaMais Ensino",
    telephone: "(71) 3123-5566",
    email: "matriculas@educamais.com",
    createdAt: "2022-12-14T09:00:00",
    address: "Av. Sete de Setembro, 1200 - Salvador/BA",
    disabled: false,
    description: "Instituição de ensino com foco em cursos técnicos e profissionalizantes para jovens e adultos.",
  },
  {
    id: 8,
    name: "SolarTech Energia",
    telephone: "(48) 4000-1212",
    email: "energia@solartech.com",
    createdAt: "2023-05-22T15:30:00",
    address: "Rua das Palmeiras, 88 - Florianópolis/SC",
    disabled: false,
    description: "Empresa de energia renovável especializada na instalação de sistemas fotovoltaicos residenciais e comerciais.",
  },
  {
    id: 9,
    name: "Prime Consultoria",
    telephone: "(51) 3555-6677",
    email: "atendimento@primeconsult.com",
    createdAt: "2023-07-01T13:45:00",
    address: "Av. Borges de Medeiros, 600 - Porto Alegre/RS",
    disabled: false,
    description: "Consultoria empresarial voltada para gestão financeira, recursos humanos e planejamento estratégico.",
  },
  {
    id: 10,
    name: "FoodPlus Alimentos",
    telephone: "(19) 3334-2221",
    email: "sac@foodplus.com",
    createdAt: "2022-10-18T11:20:00",
    address: "Rua do Comércio, 300 - Campinas/SP",
    disabled: false,
    description: "Indústria alimentícia com foco em alimentos congelados e snacks saudáveis.",
  },
  {
    id: 11,
    name: "AutoPrime Veículos",
    telephone: "(16) 3221-8899",
    email: "contato@autoprime.com",
    createdAt: "2023-08-19T10:40:00",
    address: "Av. Independência, 750 - Ribeirão Preto/SP",
    disabled: false,
    description: "Concessionária multimarcas com serviços de venda, financiamento e manutenção de veículos.",
  },
  {
    id: 12,
    name: "LogisTech Transportes",
    telephone: "(92) 4005-4444",
    email: "fretes@logistech.com",
    createdAt: "2023-01-10T08:50:00",
    address: "Rua Manaus Moderna, 400 - Manaus/AM",
    disabled: false,
    description: "Transportadora com atuação nacional, especializada em logística integrada e transporte de cargas.",
  },
  {
    id: 13,
    name: "ModaVip Confecções",
    telephone: "(84) 3111-2200",
    email: "vendas@modavip.com",
    createdAt: "2022-07-30T14:10:00",
    address: "Rua João Pessoa, 99 - Natal/RN",
    disabled: false,
    description: "Marca de moda especializada em roupas femininas e acessórios para o público jovem.",
  },
  {
    id: 14,
    name: "CleanPro Higienização",
    telephone: "(95) 3122-3344",
    email: "orcamento@cleanpro.com",
    createdAt: "2023-06-05T09:30:00",
    address: "Av. Ville Roy, 1020 - Boa Vista/RR",
    disabled: false,
    description: "Empresa especializada em higienização de estofados, carpetes e ambientes corporativos.",
  },
  {
    id: 15,
    name: "BioLife Farmacêutica",
    telephone: "(98) 4001-2323",
    email: "contato@biolife.com",
    createdAt: "2023-03-28T11:15:00",
    address: "Av. dos Holandeses, 500 - São Luís/MA",
    disabled: false,
    description: "Indústria farmacêutica voltada para medicamentos genéricos e biotecnologia.",
  },
  {
    id: 16,
    name: "Oceanic Pescados",
    telephone: "(82) 3344-6677",
    email: "sac@oceanic.com",
    createdAt: "2022-11-07T12:00:00",
    address: "Av. da Paz, 150 - Maceió/AL",
    disabled: false,
    description: "Distribuidora de pescados frescos e congelados para supermercados e restaurantes.",
  },
  {
    id: 17,
    name: "UrbanMob Mobilidade",
    telephone: "(13) 3555-8899",
    email: "contato@urbanmob.com",
    createdAt: "2023-09-02T10:50:00",
    address: "Av. Ana Costa, 420 - Santos/SP",
    disabled: false,
    description: "Startup de mobilidade urbana com soluções em aplicativos de transporte coletivo e compartilhado.",
  },
  {
    id: 18,
    name: "GreenLand Paisagismo",
    telephone: "(47) 3222-5566",
    email: "suporte@greenland.com",
    createdAt: "2023-02-14T08:30:00",
    address: "Rua Blumenau, 300 - Joinville/SC",
    disabled: false,
    description: "Empresa de jardinagem e paisagismo que desenvolve projetos residenciais e comerciais.",
  },
  {
    id: 19,
    name: "SmartPay Fintech",
    telephone: "(61) 4008-9999",
    email: "financeiro@smartpay.com",
    createdAt: "2023-05-18T13:20:00",
    address: "Setor Comercial Sul, Quadra 2 - Brasília/DF",
    disabled: false,
    description: "Fintech especializada em meios de pagamento digitais e soluções para e-commerce.",
  },
  {
    id: 20,
    name: "PetLovers Petshop",
    telephone: "(27) 3233-1122",
    email: "contato@petlovers.com",
    createdAt: "2023-07-25T11:45:00",
    address: "Av. Nossa Senhora da Penha, 800 - Vitória/ES",
    disabled: false,
    description: "Rede de petshops com serviços de banho, tosa e venda de produtos para animais de estimação.",
  },
];
